language: cpp
compiler: g++

env:
  global:
   - secure: "GuB7s4pGBaMYcrQhwYAA22MDH0J2YkVPG/ig1gwlystm0Uks4PQedKiIBEB7+qfBxnKza61NZfG5aT1U2FVqLASQjV5ndNl1Vb4lWdLXU0eU60QIp7ui5knuSu5BsoyCdpvavBdMHhIFwTbih6IZuHggLKNZQp9vftrvR92AVRI="

addons:
  coverity_scan:
    project:
      name: "jellysheep/spheresim"
      description: "Physical simulation of particle movements."
    notification_email: max.mail@dameweb.de
    build_command_prepend: "mkdir -p build && cd build && qmake ../"
    build_command: "make -j4"
    branch_pattern: master

before_install:
 - sudo apt-add-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
 - sudo apt-get update -q -y
install:
 - sudo apt-get install -q -y gcc-4.8 g++-4.8 qt5-default libqt5opengl5-dev autoconf libtool make cmake
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
 - pushd /tmp; git clone https://github.com/nanomsg/nanomsg.git; cd nanomsg; ./autogen.sh; ./configure; make -j2; make check; sudo make install; popd
 - pushd /tmp; git clone https://github.com/nanomsg/cppnanomsg.git; cd cppnanomsg; mkdir build; cd build; cmake ../; make; sudo make install; popd
script: mkdir -p build && cd build && qmake ../ && make -j4
